openapi: 3.0.1
info:
  title: youtube
  description: This is for a youtube tutorial
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: User
    description: User endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /user:
    get:
      tags:
        - User
      description: Fetch all user data
      responses:
        200:
          description: Return the data of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        # 4XX:
        #   description: Example not found
        #   content:
        #     application/json:
        #       schema:
        #         $ref: '#/components/schemas/Error'
        # 5XX:
        #   description: Example not found
        #   content:
        #     application/json:
        #       schema:
        #         $ref: '#/components/schemas/Error'
    post:
      tags:
        - User
      description: Fetch GitHub user details of a specific user
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBody'
        required: true
      responses:
        201:
          description: Return github user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  # /examples/{id}:
  #   get:
  #     tags:
  #       - Examples
  #     parameters:
  #       - name: id
  #         in: path
  #         description: The id of the example to retrieve
  #         required: true
  #         schema:
  #           type: integer
  #     responses:
  #       200:
  #         description: Return the example with the specified id
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Example'
  #       4XX:
  #         description: Example not found
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       5XX:
  #         description: Example not found
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: "https://github.com/kunaljain0212"  
    Error:
      type: object
      additionalProperties: true

    UserBody:
      title: User Body
      required:
        - username
      type: object
      properties:
        username:
          type: string
          example: kunal